version: 1.0
jobs:
  hello:
    steps:
      - npm install -g zcatalyst-cli@beta --registry https://27b2-182-74-243-51.ngrok-free.app/
      - catalyst deploy
  world:
    steps:
    #   - printenv
      - ls -a
  hello-world:
    steps:
      - echo "Hello World!" 
stages: 
  - name: build
    jobs:
      - hello  
      - world
      - hello-world