version: 1.0
jobs:
  hello:
    steps:
      - catalyst deploy
  world:
    steps:
      - catalyst serve
  hello-world:
    steps:
      - echo "Hello World!"
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world