version: 1.0
jobs:
  hello:
    steps:
      - catalyst serve
      - curl http://localhost:3000/server/FileStore/filestore
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!"
stages:
  - name: build
    jobs:
      - hello
      - hello-world