version: 1.0
jobs:
  hello:
    steps:
      - ls -a
      - catalyst
  world:
    steps:
    #   - printenv
      - which catalyst
      - ls -a
  hello-world:
    steps:
      - echo "Hello World!" 
stages: 
  - name: build
    jobs:
      - hello  
      - world
      - hello-world