version: 1.0
jobs:
  hello:
    steps:
      - catalyst serve
      - ls -a
  world:
    steps:
      - echo "Worldzz"
  hello-world:
    steps:
      - echo "Hello World!"
stages:
  - name: build
    jobs:
      - hello
      - hello-world