version: 1.0
jobs:
  hello:
    steps:
      - catalyst whoami
  world:
    steps:
      - printenv
      - catalyst deploy
  hello-world:
    steps:
      - echo "Hello World!" 
stages: 
  - name: build
    jobs:
      - hello  
        # - world
      - hello-world