version: 1.0
jobs:
  hello:
    steps:
      - catalyst
  world:
    steps:
      - printenv
      - catalyst deploy --verbose
  hello-world:
    steps:
      - echo "Hello World!" 
stages: 
  - name: build
    jobs:
      - - hello  
        - world
      - hello-world